import type { Metadata } from "next";
import localFont from "next/font/local";
import { AuthProvider } from "../context/AuthContext";
import { BookingProvider } from "../context/BookingContext"; // Import the BookingProvider

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Nordic Experiences",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <BookingProvider>
            {/* Wrap children with BookingProvider */}
            {children}
          </BookingProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
